In [2]:
# !/use/bin/env python
# encoding:utf-8
import pandas as pd
import numpy as np
import itertools
from sklearn.model_selection import KFold  
from sklearn import svm
from sklearn.model_selection import train_test_split
import math
import easy_excel
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import *
import sklearn.ensemble
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
import sys
import math
from sklearn.model_selection import GridSearchCV
import subprocess
from sklearn.utils import shuffle
import itertools
import joblib


In [7]:
"""
    cross validation
"""
datapath ='/home02/chenhuangrong/7NC.csv'
train_data = pd.read_csv(datapath, header=None, index_col=None)
for select_num in xrange(1,204):
    X = np.array(train_data)
    Y = list(map(lambda x: 1, xrange(len(train_data) / 2)))
    Y2 = list(map(lambda x: 0, xrange(len(train_data) / 2)))
    Y.extend(Y2)
    Y = np.array(Y)
    F, pval = f_classif(X, Y)
    idx = np.argsort(F)
    selected_list_=idx[::-1]
    selected_list_=selected_list_[xrange(select_num)]
    X=pd.DataFrame(X)
    X=X.iloc[:,selected_list_] 
    print select_num
    print selected_list_
    svc = svm.SVC()
    parameters = {'kernel': ['rbf'], 'C':map(lambda x:2**x,np.linspace(-2,5,7)), 'gamma':map(lambda x:2**x,np.linspace(-5,2,7))}
    clf = GridSearchCV(svc, parameters, cv=10, n_jobs=-1, scoring='accuracy')
    clf.fit(X, Y)
    C=clf.best_params_['C']
    # joblib.dump(clf,'/home02/chenhuangrong/%d_gap_%d_gram.csv'%(gap,gram))
    print clf.best_score_
    gamma=clf.best_params_['gamma']
    y_predict=cross_val_predict(svm.SVC(kernel='rbf',C=C,gamma=gamma,),X,Y,cv=10,n_jobs=-1)
    print type(y_predict)
    y_predict_prob=cross_val_predict(svm.SVC(kernel='rbf',C=C,gamma=gamma,probability=True),X,Y,cv=10,n_jobs=-1,method='predict_proba')
    predict_save=[Y.astype(int),y_predict.astype(int),y_predict_prob[:,1]]
    predict_save=np.array(predict_save).T
#     pd.DataFrame(predict_save).to_csv('/home02/chenhuangrong/blending_files/frequency_predict_%d_gram.csv'%(gram),header=None,index=False)
    ROC_AUC_area="%0.4f"%cross_val_score(svm.SVC(kernel='rbf',C=C,gamma=gamma),X,Y,cv=10,n_jobs=-1).mean()
    ACC=metrics.accuracy_score(Y,y_predict)
    precision, recall, SN, SP, GM, TP, TN, FP, FN = performance(Y, y_predict)
    F1_Score=metrics.f1_score(Y, y_predict)
    F_measure=F1_Score
    MCC=metrics.matthews_corrcoef(Y, y_predict)
    pos=TP+FN
    neg=FP+TN
    savedata=[[['svm'+"C:"+str(C)+"gamma:"+str(gamma),ACC,precision, recall,SN, SP, GM,F_measure,F1_Score,MCC,ROC_AUC_area,TP,FN,FP,TN,pos,neg]]]
    print savedata
    #     easy_excel.save("svm_crossvalidation",[str(X.shape[1])],savedata,'/home02/chenhuangrong/cross_validation_frequency_%d_gram.xls'%(gram))
    # y_predict_proba=cross_val_predict(svm.SVC(kernel='rbf',C=C,gamma=gamma,probability=True),X,Y,cv=10,method="predict_proba")
    # Y=pd.DataFrame(Y)    
    # y_predict_proba=pd.DataFrame(y_predict_proba)
    # y_predict_proba=pd.concat([Y,y_predict_proba],axis=1)
    # pd.DataFrame(y_predict_proba).to_csv('/home02/chenhuangrong/RFH_ten_cross_validation_label.csv',header=None,index=False)
    # y_predict=pd.DataFrame(y_predict)
    # y_predict_=pd.concat([Y,y_predict],axis=1)
    # pd.DataFrame(y_predict_).to_csv('/home02/chenhuangrong/RFH_ten_cross_validation_predict.csv',header=None,index=False)

1
[12761]
0.5
<type 'numpy.ndarray'>
[[['svmC:0.25gamma:0.03125', 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.66666666666666663, 0.66666666666666663, 0.0, '0.5000', 1307.0, 0.0, 1307.0, 0.0, 1307.0, 1307.0]]]
2
[12761 27299]
0.5
<type 'numpy.ndarray'>
[[['svmC:0.25gamma:0.03125', 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.66666666666666663, 0.66666666666666663, 0.0, '0.5000', 1307.0, 0.0, 1307.0, 0.0, 1307.0, 1307.0]]]
3
[12761 27299 27302]
0.5
<type 'numpy.ndarray'>
[[['svmC:0.25gamma:0.03125', 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.66666666666666663, 0.66666666666666663, 0.0, '0.5000', 1307.0, 0.0, 1307.0, 0.0, 1307.0, 1307.0]]]
4
[12761 27299 27302 18030]
0.5
<type 'numpy.ndarray'>
[[['svmC:0.25gamma:0.03125', 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.66666666666666663, 0.66666666666666663, 0.0, '0.5000', 1307.0, 0.0, 1307.0, 0.0, 1307.0, 1307.0]]]
5
[12761 27299 27302 18030 18028]
0.5
<type 'numpy.ndarray'>
[[['svmC:0.25gamma:0.03125', 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.66666666666666663, 0.66666666666666663, 0.0, '0.5000',

KeyboardInterrupt: 

In [1]:
#!/usr/bin/env python
# encoding:utf-8
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
import itertools
from sklearn.model_selection import KFold  
from sklearn import svm
from sklearn.cross_validation import train_test_split
import math
from sklearn.model_selection import *
import sklearn.ensemble
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
import sys
from sklearn.model_selection import GridSearchCV
import subprocess
import sklearn
from sklearn.externals import joblib
from sklearn.feature_selection import  f_classif


def performance(labelArr, predictArr):
    #labelArr[i] is actual value,predictArr[i] is predict value
    TP = 0.; TN = 0.; FP = 0.; FN = 0.
    for i in range(len(labelArr)):
        if labelArr[i] == 1 and predictArr[i] == 1:
            TP += 1.
        if labelArr[i] == 1 and predictArr[i] == 0:
            FN += 1.
        if labelArr[i] == 0 and predictArr[i] == 1:
            FP += 1.
        if labelArr[i] == 0 and predictArr[i] == 0:
            TN += 1.
    if (TP + FN)==0:
        SN=0
    else:
        SN = TP/(TP + FN) #Sensitivity = TP/P  and P = TP + FN
    if (FP+TN)==0:
        SP=0
    else:
        SP = TN/(FP + TN) #Specificity = TN/N  and N = TN + FP
    if (TP+FP)==0:
        precision=0
    else:
        precision=TP/(TP+FP)
    if (TP+FN)==0:
        recall==0
    else:
        recall=TP/(TP+FN)
    GM=math.sqrt(recall*SP)
    #MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    return precision,recall,SN,SP,GM,TP,TN,FP,FN
final_out_to_excel=[]
row0 = [u'特征集', u'样本个数', u'分类器', u'Accuracy', u'Precision', u'Recall', u'SN', u'SP',
                u'Gm', u'F_measure', u'F_score', u'MCC', u'ROC曲线面积', u'tp', u'fn', u'fp', u'tn']
final_out_to_excel.append(row0)
seq=[]

RFH_feature=pd.read_csv('/home02/chenhuangrong/7NC.csv',header=None,index_col=False)
RFH_feature=RFH_feature.values
RFH_positive_feature=RFH_feature[:len(RFH_feature)/2]
RFH_negative_feature=RFH_feature[len(RFH_feature)/2:]

RNA_code='ACGU'
k=1
interval=1
select_num=40
divided_num=10.0
division_num=10

def make_kmer_list(k, alphabet):
    try:
        return ["".join(e) for e in itertools.product(alphabet, repeat=k)]
    except TypeError:
        print("TypeError: k must be an inter and larger than 0, alphabet must be a string.")
        raise TypeError
    except ValueError:
        print("TypeError: k must be an inter and larger than 0")
        raise ValueError
kf = KFold(n_splits=division_num,shuffle=False)  
for select_num in xrange(30,204):
    y_pred_prob_all=[]
    y_pred_all=[]
    Y_all=[]
    ACC_all=0
    precision_all=0
    recall_all=0
    SN_all=0
    SP_all=0
    GM_all=0
    TP_all=0
    TN_all=0
    FP_all=0
    FN_all=0
    F_measure_all=0
    F1_Score_all=0
    pos_all=0
    neg_all=0
    MCC_all=0
    num_mark=0
    for train_index , test_index in kf.split(RFH_positive_feature):  
        num_mark=num_mark+1 #
        RFH_postive_train_x=pd.DataFrame(RFH_positive_feature).iloc[train_index,:]
        RFH_postive_test_y=pd.DataFrame(RFH_positive_feature).iloc[test_index,:]
        RFH_negative_train_x=pd.DataFrame(RFH_negative_feature).iloc[train_index,:]
        RFH_negative_test_y=pd.DataFrame(RFH_negative_feature).iloc[test_index,:]
        RFH_train_x=np.concatenate([RFH_postive_train_x,RFH_negative_train_x])
        RFH_test_y=np.concatenate([RFH_postive_test_y,RFH_negative_test_y])

        
#         scaler=sklearn.preprocessing.MinMaxScaler()
#         X_train_=scaler.fit_transform(RFH_train_x)        
        X_train=np.array(RFH_train_x)
        Y_train = list(map(lambda x: 1, xrange(len(X_train) / 2)))
        Y2_train = list(map(lambda x: 0, xrange(len(X_train) / 2)))
        Y_train.extend(Y2_train)
        Y_train = np.array(Y_train)
        F, pval = f_classif(X_train, Y_train)
        idx = np.argsort(F)
        selected_list_=idx[::-1]
        selected_list_=selected_list_[xrange(select_num)]
        X_train=pd.DataFrame(X_train)
        X_train=X_train.iloc[:,selected_list_]
        X_train=X_train.values
       
#         X_test_=scaler.transform(RFH_test_y)
        X_test=pd.DataFrame(RFH_test_y)
        X_test=X_test.iloc[:,selected_list_]
        X_test=X_test.values
        Y_test  = list(map(lambda x: 1, xrange(len(X_test) / 2)))
        Y2_test  = list(map(lambda x: 0, xrange(len(X_test) / 2)))
        Y_test.extend(Y2_test )
        Y_test  = np.array(Y_test)


        print "data_prepared"
        print "X_train.shape",X_train.shape
        print "X_test.shape",X_test.shape
        
        svc = svm.SVC(probability=True)
        parameters = {'kernel': ['rbf'], 'C':map(lambda x:2**x,np.linspace(-2,5,7)), 'gamma':map(lambda x:2**x,np.linspace(-5,2,7))}
        clf = GridSearchCV(svc, parameters, cv=10, n_jobs=12, scoring='accuracy')
        clf.fit(X_train, Y_train)
#         joblib.dump(clf, '/home02/chenhuangrong/another_F_score_RFH_PSNP%d.model_%d'%(num_mark,select_num))
        C=clf.best_params_['C']
        y_pred_prob=clf.predict_proba(X_test)

        gamma=clf.best_params_['gamma']
        print 'c:',C,'gamma:',gamma
        y_pred=clf.predict(X_test)

        y_pred_prob_all.extend(y_pred_prob)
        y_pred_all.extend(y_pred)
        Y_all.extend(Y_test)
        ACC=metrics.accuracy_score(Y_test,y_pred)
        print ACC
        precision, recall, SN, SP, GM, TP, TN, FP, FN = performance(Y_test, y_pred) 
        F1_Score=metrics.f1_score(Y_test, y_pred)
        F_measure=F1_Score
        MCC=metrics.matthews_corrcoef(Y_test, y_pred)

        pos=TP+FN
        neg=FP+TN
        ACC_all=ACC_all+ACC
#         print "ACC_all:",ACC_all
        precision_all=precision_all+precision
        recall_all=recall_all+recall
        SN_all=SN_all+SN
        SP_all=SP_all+SP
        GM_all=GM_all+GM
        TP_all=TP_all+TP
        TN_all=TN_all+TN
        FP_all=FP_all+FP
        FN_all=FN_all+FN
        F_measure_all=F_measure_all+F_measure
        F1_Score_all=F1_Score_all+F1_Score
        pos_all=pos_all+pos
        neg_all=neg_all+neg
        MCC_all=MCC_all+MCC
    all_y=[np.array(Y_all).astype(int),np.array(y_pred_all).astype(int),np.array(y_pred_prob_all).astype(list)[:,1]]
#     pd.DataFrame(np.matrix(all_y).T).to_csv('/home02/chenhuangrong/another_F_score_PsCPm6APred_independent_test_with_F_Score%d_%d.csv'%(num_mark,select_num),header=None,index=False)
    fpr, tpr, thresholds = roc_curve(np.array(Y_all).T, list(np.array(y_pred_prob_all).astype(list)[:,1]))
    roc_auc = auc(fpr, tpr)  
    savedata=[str(X_train.shape[1])+"select_num:"+str(select_num),"正"+str(pos_all)+'负'+str(neg_all),'svm'+"C:"+str(C)+"gamma:"+str(gamma),ACC_all/divided_num,precision_all/divided_num, recall_all/divided_num,SN_all/divided_num,
                SP_all/divided_num, GM_all/divided_num,F_measure_all/divided_num,F1_Score_all/divided_num,MCC_all/divided_num,roc_auc,TP_all,
                FN_all,FP_all,TN_all]
    print savedata
    final_out_to_excel.append(savedata)
pd.DataFrame(final_out_to_excel).to_excel("/home02/chenhuangrong/RFH_F_score_%d.xlsx"%select_num,sheet_name="F_score",index=False,header=False)

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   154   342 ..., 32357 32359 32422] are constant.
  UserWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


c: 0.25 gamma: 0.03125
0.507633587786
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   361   393 ..., 32173 32185 32422] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.507633587786
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   393   425 ..., 32294 32373 32422] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.5
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   357   393 ..., 32173 32185 32422] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.496183206107
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   393   425 ..., 32214 32310 32422] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.496183206107
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   393   425 ..., 32173 32185 32422] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.5
data_prepared
X_train.shape (2352, 30)
X_test.shape (262, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   365   393 ..., 32422 32485 32493] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.503816793893
data_prepared
X_train.shape (2354, 30)
X_test.shape (260, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   393   425 ..., 32185 32422 32585] are constant.
  UserWarning)


c: 0.25 gamma: 0.03125
0.503846153846
data_prepared
X_train.shape (2354, 30)
X_test.shape (260, 30)


/usr/local/lib/python2.7/dist-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [  106   343   393 ..., 32366 32375 32422] are constant.
  UserWarning)


KeyboardInterrupt: 