In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.model_selection import KFold  
from sklearn import svm
from sklearn.cross_validation import train_test_split
import math
import easy_excel
from sklearn.model_selection import *
import sklearn.ensemble
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
import sys
from sklearn.model_selection import GridSearchCV

y_pred_prob_all=[]
y_pred_all=[]
Y_all=[]
ACC_all=0
precision_all=0
recall_all=0
SN_all=0
SP_all=0
GM_all=0
TP_all=0
TN_all=0
FP_all=0
FN_all=0
F_measure_all=0
F1_Score_all=0
pos_all=0
neg_all=0
MCC_all=0

def performance(labelArr, predictArr):
    #labelArr[i] is actual value,predictArr[i] is predict value
    TP = 0.; TN = 0.; FP = 0.; FN = 0.
    for i in range(len(labelArr)):
        if labelArr[i] == 1 and predictArr[i] == 1:
            TP += 1.
        if labelArr[i] == 1 and predictArr[i] == 0:
            FN += 1.
        if labelArr[i] == 0 and predictArr[i] == 1:
            FP += 1.
        if labelArr[i] == 0 and predictArr[i] == 0:
            TN += 1.
    if (TP + FN)==0:
        SN=0
    else:
        SN = TP/(TP + FN) #Sensitivity = TP/P  and P = TP + FN
    if (FP+TN)==0:
        SP=0
    else:
        SP = TN/(FP + TN) #Specificity = TN/N  and N = TN + FP
    if (TP+FP)==0:
        precision=0
    else:
        precision=TP/(TP+FP)
    if (TP+FN)==0:
        recall==0
    else:
        recall=TP/(TP+FN)
    GM=math.sqrt(recall*SP)
    #MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    return precision,recall,SN,SP,GM,TP,TN,FP,FN
seq=[]
m6a_2614_sequence="/home02/chenhuangrong/AthMethPre.csv"
RNA_code='ACGU'
k=1
interval=1
divided_num=10.0
division_num=10
seq=pd.read_csv(m6a_2614_sequence,header=None,index_col=None)
seq=seq.values
positive_seq=seq[0:1307,:]
# X_train, X_test, y_train, y_test = cross_validation.train_test_split(train_data, train_target, test_size=0.1, random_state=0)
negative_seq=seq[1307:2614,:]
kf = KFold(n_splits=division_num,shuffle=False)  
for train_index , test_index in kf.split(positive_seq):  
    print train_index,test_index

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[ 131  132  133 ..., 1304 1305 1306] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130]
[   0    1    2 ..., 1304 1305 1306] [131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148
 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166
 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184
 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202
 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220
 221 222 223 224 225 226 227

In [27]:
import os
import pandas as pd
import subprocess
# cmd = '/home/qqin/bin/ntthal -mv %s -dv %s -d %s -n %s -s1 %s -s2 %s -a %s -path %s'% (mv, dv, d, n, seq1, seq2, align_mode,thermo_path)
# out, align = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()

# child=subprocess.Popen('cd /home01/chenhuangrong/mRMR/',shell=True)
# child.wait
# out=subprocess.Popen("ls",stdout=subprocess.PIPE).communicate()
# print out
# child2=subprocess.Popen('java -jar arff2csv.jar 98D_m6a.arff four.csv',shell=True)
# child2.wait
# child3=subprocess.Popen('./mrmr -i 4.csv -n 20 >4.mrmrout',shell=True)
# child3.wait
# child4=subprocess.Popen('java -jar mrmr_to_arff.jar 4.mrmrout final.arff -f 20 -c 7 1 2 3 4 5 6 7',shell=True)
# child4.wait
# os.sysem("chmod 777 /home01/chenhuangrong/mRMR/*")
# os.system(".//home01/chenhuangrong/mRMR/mrmr -i /home01/chenhuangrong/mRMR/4.csv -n 20 >/home01/chenhuangrong/mRMR/4.mrmrout")
# os.system("java -jar /home01/chenhuangrong/mRMR/mrmr_to_arff.jar 4.mrmrout /home01/chenhuangrong/mRMR/4.csv /home01/chenhuangrong/mRMR/final.arff -f 20 -c 7 1 2 3 4 5 6 7")
# data=pd.read_csv('/home01/chenhuangrong/mRMR/4.csv')
# print data


('4.mrmrout\nchange_svm_parameter.ipynb\nchr_mlens.ipynb\ndraw_multi_ROC.ipynb\ndraw_single_ROC.ipynb\neasy_excel.py\neasy_excel.pyc\nentropy of informarion.ipynb\nfetch_local_frequency.ipynb\nfetch_position_specific_feature.ipynb\nget_PSTNP_representation.ipynb\ng_gap_PSTNP.ipynb\nheatmap.ipynb\nindependent_test.ipynb\nloca_occurence_frequency_and_global_occurence_frequency.ipynb\nmerge_features.ipynb\nmyfirstjupyterfile.ipynb\nnew_PSTNP_.ipynb\nN_mer_PSTNP.ipynb\nposition_specific_global_occurence_frequency.ipynb\nrandomForestClassifier_.ipynb\nRFH_PSTNP(1)_independent_test.ipynb\nRFH_ten_cross_validation_svm.ipynb\nroc_auc.ipynb\nROC.ipynb\nTest_file.ipynb\nUntitled.ipynb\nvote_PSTNP.ipynb\n', None)


In [8]:
import pandas as pd
d0=[[1,2,3,4,5],[6,7,8,9,10]]
with pd.ExcelWriter('/home02/chenhuangrong/final.xls') as writer:
    pd.DataFrame(d0).to_excel(writer,'sheet')

In [46]:
''.join([1,2])
p=[e*2+e for e in xrange(3)]
print type(p)
print "".join()

TypeError: sequence item 0: expected string, int found

In [12]:
import numpy as np
p=np.array([[1,2,3],[4,5,6]])
print p

[[1 2 3]
 [4 5 6]]


In [17]:
import os 
import numpy as np
import pandas as pd
def generating_integrated_training(file_dir,samples_size):   
    Y=[1 for e in xrange(samples_size)]
    Y2=[0 for e in xrange(samples_size)]
    Y.extend(Y2)
    X=[]
    for root, dirs, files in os.walk(file_dir):  
#         print(root) #当前目录路径  
#         print(dirs) #当前路径下所有子目录  
        for e in files:
            data=pd.read_csv(root+'/'+e,header=None,index_col=False)
            data=data.values[:,1]
            X.append(data)
    print len(X)
    X=np.array(X).T
    return X
X=generating_integrated_training('/home02/chenhuangrong/integrated_training',1307)
svc = svm.SVC()
parameters = {'kernel': ['rbf'], 'C':map(lambda x:2**x,np.linspace(-2,5,7)), 'gamma':map(lambda x:2**x,np.linspace(-5,2,7))}
clf = GridSearchCV(svc, parameters, cv=10, n_jobs=-1, scoring='accuracy')
clf.fit(X, Y)
C=clf.best_params_['C']
# joblib.dump(clf,'/home02/chenhuangrong/%d_gap_%d_gram.csv'%(gap,gram))
print clf.best_score_
gamma=clf.best_params_['gamma']
y_predict=cross_val_predict(svm.SVC(kernel='rbf',C=C,gamma=gamma,),X,Y,cv=10,n_jobs=-1)
print type(y_predict)
y_predict_prob=cross_val_predict(svm.SVC(kernel='rbf',C=C,gamma=gamma,probability=True),X,Y,cv=10,n_jobs=-1,method='predict_proba')
predict_save=[Y.astype(int),y_predict.astype(int),y_predict_prob[:,1]]
predict_save=np.array(predict_save).T
pd.DataFrame(predict_save).to_csv('/home02/chenhuangrong/blending_files/frequency_predict_%d_gram.csv'%(gram),header=None,index=False)
ROC_AUC_area="%0.4f"%cross_val_score(svm.SVC(kernel='rbf',C=C,gamma=gamma),X,Y,cv=10,n_jobs=-1).mean()
ACC=metrics.accuracy_score(Y,y_predict)
precision, recall, SN, SP, GM, TP, TN, FP, FN = performance(Y, y_predict)
F1_Score=metrics.f1_score(Y, y_predict)
F_measure=F1_Score
MCC=metrics.matthews_corrcoef(Y, y_predict)
pos=TP+FN
neg=FP+TN
savedata=[[['svm'+"C:"+str(C)+"gamma:"+str(gamma),ACC,precision, recall,SN, SP, GM,F_measure,F1_Score,MCC,ROC_AUC_area,TP,FN,FP,TN,pos,neg]]]
print savedata
return ACC

21


In [36]:
from sklearn.utils import shuffle
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.array([1,2,3])
X=shuffle(X,random_state=4)
print X


[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [36]:
import pandas as pd
import numpy as np
import copy as cp
class F_score:
    index=[]
    dimension=1
    def fit_transform(self,train_data,dimension=1):
        train_positive_data=train_data[0:len(train_data)/2]
        train_negative_data=train_data[len(train_data)/2:len(train_data)]
        train_positive_len=len(train_positive_data)
        train_negative_len=len(train_negative_data)
        train_positive_vector=reduce(lambda x,y:np.array(x)+np.array(y),train_positive_data)
        train_vector=reduce(lambda x,y:np.array(x)+np.array(y),train_data)
        train_negative_vector=reduce(lambda x,y:np.array(x)+np.array(y),train_negative_data)
        numerator=np.array([math.pow(e,2) for e in (train_positive_vector-train_vector)])+np.array([math.pow(e,2) for e in (train_negative_vector-train_vector)])
        numerator=np.array(numerator)
        positive_denominator=reduce(lambda x,y:x+y,np.array([map(lambda x:math.pow(x,2),(e-train_positive_vector)) for e in train_positive_data]))*(1.0/(train_positive_len-1))
        negative_denominator=reduce(lambda x,y:x+y,np.array([map(lambda x:math.pow(x,2),(e-train_negative_vector)) for e in train_negative_data]))*(1.0/(train_negative_len-1))
        denominator=positive_denominator+negative_denominator
        F_score_values=numerator/denominator
        F_score_values=pd.DataFrame(F_score_values).fillna(0)
#         print F_score_values.sort(0, ascending=False)
        F_score_values=F_score_values.sort_values(by=[0],ascending=False)
        train_index=list(F_score_values.index)[0:dimension]
        self.index=cp.deepcopy(train_index)
        self.dimension=dimension
        train_data_final=pd.DataFrame(train_data).iloc[:,train_index]
        return np.array(train_data_final)
    def __init__(self):
        print "F_score instance success"
    def transform(self,test_data):
        test_data=pd.DataFrame(test_data)
        test_data_final=test_data.iloc[:,self.index]
        return np.array(test_data_final)

In [48]:
#!/usr/bin/env python
# encoding:utf-8
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
import itertools
from sklearn.model_selection import KFold  
from sklearn import svm
from sklearn.cross_validation import train_test_split
import math
from sklearn.model_selection import *
import sklearn.ensemble
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
import sys
from sklearn.model_selection import GridSearchCV
import subprocess
import sklearn


def performance(labelArr, predictArr):
    #labelArr[i] is actual value,predictArr[i] is predict value
    TP = 0.; TN = 0.; FP = 0.; FN = 0.
    for i in range(len(labelArr)):
        if labelArr[i] == 1 and predictArr[i] == 1:
            TP += 1.
        if labelArr[i] == 1 and predictArr[i] == 0:
            FN += 1.
        if labelArr[i] == 0 and predictArr[i] == 1:
            FP += 1.
        if labelArr[i] == 0 and predictArr[i] == 0:
            TN += 1.
    if (TP + FN)==0:
        SN=0
    else:
        SN = TP/(TP + FN) #Sensitivity = TP/P  and P = TP + FN
    if (FP+TN)==0:
        SP=0
    else:
        SP = TN/(FP + TN) #Specificity = TN/N  and N = TN + FP
    if (TP+FP)==0:
        precision=0
    else:
        precision=TP/(TP+FP)
    if (TP+FN)==0:
        recall==0
    else:
        recall=TP/(TP+FN)
    GM=math.sqrt(recall*SP)
    #MCC = (TP*TN-FP*FN)/math.sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    return precision,recall,SN,SP,GM,TP,TN,FP,FN
final_out_to_excel=[]
row0 = [u'特征集', u'样本个数', u'分类器', u'Accuracy', u'Precision', u'Recall', u'SN', u'SP',
                u'Gm', u'F_measure', u'F_score', u'MCC', u'ROC曲线面积', u'tp', u'fn', u'fp', u'tn']
final_out_to_excel.append(row0)
seq=[]
m6a_2614_sequence="/home01/chenhuangrong/ROC/m6a_data.txt"

RFH_feature=pd.read_csv('/home01/chenhuangrong/ROC/position_specific.csv',header=None,index_col=False)
RFH_feature=RFH_feature.values
RFH_positive_feature=RFH_feature[:len(RFH_feature)/2]
RFH_negative_feature=RFH_feature[len(RFH_feature)/2:]

RNA_code='ACGU'
k=1
interval=1
select_num=40
divided_num=10.0
division_num=10
fh=open(m6a_2614_sequence)
for line in fh:
    if line.startswith('>'):
        continue
    else:
        seq.append(line.replace('\n',''))
fh.close()

def make_kmer_list(k, alphabet):
    try:
        return ["".join(e) for e in itertools.product(alphabet, repeat=k)]
    except TypeError:
        print("TypeError: k must be an inter and larger than 0, alphabet must be a string.")
        raise TypeError
    except ValueError:
        print("TypeError: k must be an inter and larger than 0")
        raise ValueError
positive_seq=seq[:len(seq)/2]
# X_train, X_test, y_train, y_test = cross_validation.train_test_split(train_data, train_target, test_size=0.1, random_state=0)
negative_seq=seq[len(seq)/2:]
kf = KFold(n_splits=division_num,shuffle=False)  
for select_num in xrange(150,151):
    y_pred_prob_all=[]
    y_pred_all=[]
    Y_all=[]
    ACC_all=0
    precision_all=0
    recall_all=0
    SN_all=0
    SP_all=0
    GM_all=0
    TP_all=0
    TN_all=0
    FP_all=0
    FN_all=0
    F_measure_all=0
    F1_Score_all=0
    pos_all=0
    neg_all=0
    MCC_all=0
    for train_index , test_index in kf.split(positive_seq):  
        positive_df=pd.DataFrame(positive_seq)
        positive_x_train=positive_df.iloc[train_index,:]
        positive_y_train=positive_df.iloc[test_index,:]
        negative_df=pd.DataFrame(negative_seq)
        negative_x_train=negative_df.iloc[train_index,:]
        negative_y_train=negative_df.iloc[test_index,:]
        positive_negative_x_train=pd.concat([positive_x_train,negative_x_train],axis=0)
        positive_negative_y_train=pd.concat([positive_y_train,negative_y_train],axis=0)
        
        RFH_postive_train_x=pd.DataFrame(RFH_positive_feature).iloc[train_index,:]
        RFH_postive_test_y=pd.DataFrame(RFH_positive_feature).iloc[test_index,:]
        RFH_negative_train_x=pd.DataFrame(RFH_positive_feature).iloc[train_index,:]
        RFH_negative_test_y=pd.DataFrame(RFH_positive_feature).iloc[test_index,:]
        RFH_train_x=np.concatenate([RFH_postive_train_x,RFH_negative_train_x])
        RFH_test_y=np.concatenate([RFH_postive_test_y,RFH_negative_test_y])
        final_seq_value=[[0 for ii in xrange(len(seq[0])-interval)] for jj in xrange(len(positive_negative_x_train))]
        code_values=make_kmer_list(interval,RNA_code)
        code_len=len(code_values)
        positive_seq_value=[[0 for jj in xrange(len(seq[0])-interval)] for ii in xrange(code_len)]
        negative_seq_value=[[0 for jj in xrange(len(seq[0])-interval)] for ii in xrange(code_len)]
        for i,line_value in enumerate(positive_x_train.values):
            for j,code_value in enumerate(line_value[0]):
                if j<= len(line_value[0])-interval-1 :
                    for p,c_value in enumerate(code_values):
                        if c_value==line_value[0][j:j+interval]:
                            positive_seq_value[p][j]+=1
        positive_seq_value=np.matrix(positive_seq_value)*1.0/(len(seq)/2)
        for i,line_value in enumerate(negative_x_train.values):
            for j,code_value in enumerate(line_value[0]):
                if j<= len(line_value[0])-interval-1 :
                    for p,c_value in enumerate(code_values):
                        if c_value==line_value[0][j:j+interval]:
                            negative_seq_value[p][j]+=1
        negative_seq_value=np.matrix(negative_seq_value)*1.0/(len(seq)/2)
        for i,line_value in enumerate(positive_negative_x_train.values):
            for j,code_value in enumerate(line_value[0]):
                if j<= len(line_value[0])-interval-1 :
                    for p,c_value in enumerate(code_values):
                        if c_value==line_value[0][j:j+interval]:
                              final_seq_value[i][j]=positive_seq_value[p,j]-negative_seq_value[p,j]
        y_final_seq_value=[[0 for ii in xrange(len(seq[0])-interval)] for jj in xrange(len(positive_negative_y_train))]
        

        for i,line_value in enumerate(positive_negative_y_train.values):
            for j,code_value in enumerate(line_value[0]):
                if j<= len(line_value[0])-interval-1 :
                    for p,c_value in enumerate(code_values):
                        if c_value==line_value[0][j:j+interval]:
                              y_final_seq_value[i][j]=positive_seq_value[p,j]-negative_seq_value[p,j]
        
        f=F_score()
        X_train=pd.DataFrame(final_seq_value)
        RFH_train_x=pd.DataFrame(RFH_train_x)
        X_train_=pd.concat([X_train,RFH_train_x],axis=1)
        scaler=sklearn.preprocessing.MinMaxScaler()
        X_train_=pd.DataFrame(X_train_)
        X_train_=scaler.fit_transform(X_train_)
        X_train_=np.array(X_train_)
        X_train_=f.fit_transform(X_train_,select_num)
        X_train=np.array(X_train_)
        Y_train = list(map(lambda x: 1, xrange(len(final_seq_value) / 2)))
        Y2_train = list(map(lambda x: 0, xrange(len(final_seq_value) / 2)))
        Y_train.extend(Y2_train)
        Y_train = np.array(Y_train)

        X_test=pd.DataFrame(y_final_seq_value)
        RFH_test_y=pd.DataFrame(RFH_test_y)
        X_test_=pd.concat([X_test,RFH_test_y],axis=1)
        X_test_=pd.DataFrame(X_test_)
        X_test_=scaler.transform(X_test_)
        X_test_=np.array(X_test_)
        X_test_=f.transform(X_test_)
        X_test=np.array(X_test_)
        Y_test  = list(map(lambda x: 1, xrange(len(y_final_seq_value) / 2)))
        Y2_test  = list(map(lambda x: 0, xrange(len(y_final_seq_value) / 2)))
        Y_test.extend(Y2_test )
        Y_test  = np.array(Y_test)
        print "PCA success"
        print select_num


        
        
        print "already get train and test data"
        svc = svm.SVC(probability=True)
        parameters = {'kernel': ['rbf'], 'C':map(lambda x:2**x,np.linspace(-2,5,2)), 'gamma':map(lambda x:2**x,np.linspace(-5,2,2))}
        print "begin ten cross validation"
        clf = GridSearchCV(svc, parameters, cv=5, n_jobs=12, scoring='accuracy')
        clf.fit(X_train, Y_train)
        C=clf.best_params_['C']
        y_pred_prob=clf.predict_proba(X_test)

        gamma=clf.best_params_['gamma']
        print 'c:',C,'gamma:',gamma
        y_pred=clf.predict(X_test)

        y_pred_prob_all.extend(y_pred_prob)
        y_pred_all.extend(y_pred)
        Y_all.extend(Y_test)
        ACC=metrics.accuracy_score(Y_test,y_pred)
        print ACC
        precision, recall, SN, SP, GM, TP, TN, FP, FN = performance(Y_test, y_pred) 
        F1_Score=metrics.f1_score(Y_test, y_pred)
        F_measure=F1_Score
        MCC=metrics.matthews_corrcoef(Y_test, y_pred)

        pos=TP+FN
        neg=FP+TN
        ACC_all=ACC_all+ACC
        print "ACC_all:",ACC_all
        precision_all=precision_all+precision
        recall_all=recall_all+recall
        SN_all=SN_all+SN
        SP_all=SP_all+SP
        GM_all=GM_all+GM
        TP_all=TP_all+TP
        TN_all=TN_all+TN
        FP_all=FP_all+FP
        FN_all=FN_all+FN
        F_measure_all=F_measure_all+F_measure
        F1_Score_all=F1_Score_all+F1_Score
        pos_all=pos_all+pos
        neg_all=neg_all+neg
        MCC_all=MCC_all+MCC
    all_y=[np.array(Y_all).astype(int),np.array(y_pred_all).astype(int),np.array(y_pred_prob_all).astype(list)[:,1]]
    pd.DataFrame(np.matrix(all_y).T).to_csv('/home01/chenhuangrong/ROC/test_PsCPm6APred_independent_test_with_F_Score%d.csv'%select_num,header=None,index=False)
    fpr, tpr, thresholds = roc_curve(np.array(Y_all).T, list(np.array(y_pred_prob_all).astype(list)[:,1]))
    roc_auc = auc(fpr, tpr)
   
    savedata=[str(X_train.shape[1])+"select_num:"+str(select_num),"正"+str(pos_all)+'负'+str(neg_all),'svm'+"C:"+str(C)+"gamma:"+str(gamma),ACC_all/divided_num,precision_all/divided_num, recall_all/divided_num,SN_all/divided_num,
                SP_all/divided_num, GM_all/divided_num,F_measure_all/divided_num,F1_Score_all/divided_num,MCC_all/divided_num,roc_auc,TP_all,
                FN_all,FP_all,TN_all]
    final_out_to_excel.append(savedata)
print savedata
pd.DataFrame(final_out_to_excel).to_excel("/home01/chenhuangrong/ROC/test_PsCPm6APred_PSNP_F_score.xlsx",sheet_name="F_score",index=False,header=False)

F_score instance success
PCA success
150
already get train and test data
begin ten cross validation


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:20: RuntimeWarning: invalid value encountered in divide


c: 32.0 gamma: 0.03125
0.984732824427
ACC_all: 0.984732824427
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.980916030534
ACC_all: 1.96564885496
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.954198473282
ACC_all: 2.91984732824
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.961832061069
ACC_all: 3.88167938931
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.961832061069
ACC_all: 4.84351145038
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.950381679389
ACC_all: 5.79389312977
F_score instance success
PCA success
150
already get train and test data
begin ten cross validation
c: 32.0 gamma: 0.03125
0.96183206

In [42]:
len(X_test)

260

In [45]:

seq=[]
physical_chemical_properties_path="/home01/chenhuangrong/ROC/physical_chemical_properties.txt"#sys.argv[1]
data=pd.read_csv(physical_chemical_properties_path,header=None,index_col=None)#read the phisical chemichy proporties
prop_key=data.values[:,0]
prop_data=data.values[:,1:]
prop_data=np.matrix(prop_data)
prop_data_transformed=sklearn.preprocessing.StandardScaler().fit_transform(prop_data)
print prop_data_transformed

[[-0.86155507 -0.68851904 -1.16271988  1.38640918 -1.89580047 -0.270232
   1.77218458  0.98016896  0.30405528  1.39630954]
 [-0.14854398 -1.69834696  1.54483439  0.51006165  0.55533549  0.34744115
  -0.27584706 -0.32532822  0.23553578 -0.26885463]
 [ 0.56446712  0.         -0.81335804  0.1266596   0.0957475  -0.88790515
   0.13554795  0.84627181  0.09849678  0.28620009]
 [-0.14854398 -0.64261777 -0.98803896  0.8934637   1.01492348  0.9651143
   0.62743327  1.46554612 -0.86077621  1.39630954]
 [-1.93107171  0.64261777  0.49674887  0.34574649  0.86172748 -0.270232
   0.15343468 -0.59312252 -0.17558122  0.14743641]
 [ 0.80213748  0.09180254 -0.55133666 -1.40694858 -0.2106445   0.34744115
  -1.16571233 -0.91112824  2.08556226 -1.37896408]
 [ 0.56446712  1.65244569  2.15621762 -2.00943751 -0.82342849 -2.7409246
   0.06400099  0.81279753 -0.99781521 -0.13009095]
 [ 0.56446712  0.         -0.81335804  0.1266596   0.0957475  -0.88790515
   0.13554795  0.84627181  0.09849678  0.28620009]
 [ 1.5

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
